configServiceAddress:
  ip: 127.0.0.1
  port: 9001
grpcOuterAddress:
  #ip: 127.0.0.1
  port: 9007
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9007
moduleName: msp-admin-service
infraServerPort: 9557

logfile:
  path: /var/log/msp-admin-service/runtime.log
  maxSizeMb: 512
  maxBackups: 4
  compress: true
