configServiceAddress:
  ip: 127.0.0.1
  port: 9001
grpcOuterAddress:
  #ip: 127.0.0.1
  port: 9007
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9007
webSocketAddress:
  ip: 0.0.0.0
  port: 9100
moduleName: admin
